// Test fixture generated by the original encoder, never used by the live observer.
#include <iostream>
#include <iomanip>
#include <sstream>
#include "team_communication_protocol.h"
#include "booster_interface/third_party/nlohmann_json/json.hpp"
std::string hex(const std::vector<uint8_t>& bytes) {
    std::ostringstream stream;
    for (auto byte : bytes) stream << std::hex << std::setw(2) << std::setfill('0') << int(byte);
    return stream.str();
}
int main() {
    std::string secret; std::cin >> secret;
    team_communication_protocol::AuthenticationKey key;
    if (!team_communication_protocol::parseAuthenticationKey(secret, key)) return 1;
    TeamDiscoveryMsg discovery; discovery.teamId=1; discovery.playerId=2; discovery.bootId=123;
    discovery.sequence=5; discovery.statePort=30022;
    TeamCommunicationMsg state; state.teamId=1; state.playerId=2; state.bootId=123; state.sequence=7;
    state.playerRole=1; state.isAlive=true; state.isLead=true; state.ballOwnerId=2;
    std::cout << nlohmann::json{{"discovery",hex(team_communication_protocol::encodeDiscovery(discovery,key))},
                              {"state",hex(team_communication_protocol::encodeState(state,key))}}.dump();
}
