camera:
  color_topic: /boostercamera/head/rgb
  depth_topic: /boostercamera/head/depth
  intrin_topic: /boostercamera/head/rgb/camera_info
  intrin:
    fx: 208.7129407302772
    fy: 208.8833792948362
    cx: 272.0
    cy: 224.0
    distortion_model: 0
    distortion_coeffs: []
  extrin:
  - - 0.99999177585005
    - 0.0024227786925726824
    - 0.003252441493753969
    - 4.0802399742067125e-05
  - - -0.0024065094178527726
    - 0.9999846202254965
    - -0.004996801466069975
    - 0.00621565734107139
  - - -0.003264497616060189
    - 0.004988933340539734
    - 0.9999822266417732
    - 0.004043625278934274
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  pitch_compensation: 0
  yaw_compensation: 0
  z_compensation: 0
  image_size:
  - 544
  - 448
detection_model:
  model_path: ./src/vision/model/best_digua_second_10.3.engine
  confidence_threshold: 0.2
  nms_threshold: 0.4
  classnames:
  - Ball
  - Goalpost
  - Person
  - LCross
  - TCross
  - XCross
  - PenaltyPoint
  - Opponent
  - BRMarker
  post_process:
    single_ball_assumption: false
    confidence_thresholds:
      Ball: 0.2
      Goalpost: 0.2
      Person: 0.2
      LCross: 0.1
      TCross: 0.1
      XCross: 0.1
      PenaltyPoint: 0.1
      Opponent: 0.5
      BRMarker: 0.2
segmentation_model:
  model_path: ./src/vision/model/best_seg_orin_10.3.engine
  confidence_threshold: 0.3
  nms_threshold: 0.9
use_depth: false
ball_pose_estimator:
  use_depth: false
  radius: 0.109
  down_sample_leaf_size: 0.01
  cluster_distance_threshold: 0.01
  fitting_distance_threshold: 0.01
  minimum_cluster_size: 150
  filter_distance: 1.2
  check_ball_height: true
human_like_pose_estimator:
  use_depth: false
  down_sample_leaf_size: 0.01
  fitting_distance_threshold: 0.01
  statistic_outlier_multiplier: 0.01
field_marker_pose_estimator:
  refine: false
  line_segment_area_threshold: 75
calibration:
  sync_max_time_diff_ms: 1400
  offset:
    exclude_distance: 2.0
    zero_translation: true
    field_marker_path: ./src/vision/config/field.yaml
  handeye:
    calibration_time: 2026-09-14-17-16-50
    reprojection_error: 1.1183443687395673
  auto_calibrate: true
misc:
  save_data_nonstationary: true
robot_name: ''
